<?php

/**
 * @file
 * Contains the primary logic for the Reports module.
 */

/**
 * Implements hook_help().
 * Proporciona una descripción del módulo en la interfaz de administración.
 */
function reports_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.reports':
      return '<p>' . t('This module provides custom reports functionality.') . '</p>';
  }
}

